-- Test database init: same as init-db.sql but for yurdelo_test
CREATE ROLE app_user WITH LOGIN PASSWORD '29203f28eb2d4028704444ea4151d86a5a0e0df2';
GRANT CONNECT ON DATABASE yurdelo_test TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_user;
